spring:
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: Tkm Consent Manager
server:
  port: ${serverPort}
  servlet:
    context-path: /tkm-ms-consent-manager

#logging:
#  pattern:
#    level: "[${APP_NAME},%X{traceId},%X{spanId},%X{spanExportable}]"