spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}
    username: ${keyvault.consentMDbUsername}
    password: ${keyvault.consentMDbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: Tkm Consent Manager ${HOSTNAME:0}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
  pattern:
    level: "${LOGGING_PATTERN:%p [${spring.application.name}][%X{traceId}]}"

azure:
  keyvault:
    enabled: true
    client-id: ${AZURE_KEYVAULT_CLIENT_ID}
    client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
    tenant-id: ${AZURE_KEYVAULT_TENANT_ID}
    uri: ${AZURE_KEYVAULT_URI}

keyvault:
  eventhubLogSaslJaasConfig: ${${profile:prod}-eventhubLogSaslJaasConfig}
  consentMDbUsername: ${${profile:prod}-consentMDbUsername}
  consentMDbPassword: ${${profile:prod}-consentMDbPassword}

management:
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"