spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_PORT}/consent_manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: Tkm Consent Manager ${INSTANCE_NUMBER:0}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /tkm-ms-consent-manager

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
  pattern:
    level: "${LOGGING_PATTERN:%p [${spring.application.name}][%X{traceId}]}"