openapi: 3.0.1
info:
  title: tkm-ms-consent-manager
  description: "RESTful APIs provided for consent management"
  version: '1.1.0'
servers:
  - url: http://localhost:2000/tkm-ms-consent-manager
  - url: http://tkm-sit/tkm-ms-consent-manager
  - url: http://tkm-uat/tkm-ms-consent-manager
  - url: http://tkm-prod/tkm-ms-consent-manager
tags:
  - name: authenticated
    description: exposed via APIM
  - name: restricted
    description: only for internal use
paths:
  /consent:
    post:
      tags:
        - authenticated
      summary: Create or change consent
      parameters:
        - in: header
          name: Tax-Code
          schema:
            type: string
            minLength: 16
            maxLength: 16
          required: true
        - in: header
          name: Client-Id
          schema:
            type: string
            maxLength: 70
          required: true
      operationId: saveConsent
      description: Client identification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consent'
      responses:
        '200':
          description: Success
          headers:
            Request-Id:
              schema:
                type: string
                minLength: 16
                maxLength: 16
                example: 937aee55bbabd29b
              required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentResponse'
        '400':
          description: Bad Request
          headers:
            Request-Id:
              schema:
                type: string
                minLength: 16
                maxLength: 16
                example: 937aee55bbabd29b
              required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentError'
        '500':
          description: Internal Server Error
          headers:
            Request-Id:
              schema:
                type: string
                minLength: 16
                maxLength: 16
                example: 937aee55bbabd29b
              required: true
    get:
      tags:
        - authenticated
      summary: Get consent
      operationId: getConsent
      parameters:
        - in: header
          name: Tax-Code
          schema:
            type: string
            minLength: 16
            maxLength: 16
          required: true
          description: User tax code
        - in: query
          name: hpan
          schema:
            type: string
            minLength: 64
            maxLength: 64
          required: false
        - in: header
          name: Client-Id
          schema:
            type: string
            maxLength: 70
          description: User client id
        - in: query
          name: services
          schema:
            $ref: '#/components/schemas/ServiceEnum'
          required: false
          description: List of the service involved by the modified. If blank the changes is referred to all services
          example: Service1,Service2,Service3
      responses:
        '200':
          description: Success
          headers:
            Request-Id:
              schema:
                type: string
                minLength: 16
                maxLength: 16
                example: 937aee55bbabd29b
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentResponse'
        '400':
          description: Bad Request
          headers:
            Request-Id:
              schema:
                type: string
                minLength: 16
                maxLength: 16
                example: 937aee55bbabd29b
              required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentError'
        '404':
          description: Tax Code or Hpan not found
          headers:
            Request-Id:
              schema:
                type: string
                minLength: 16
                maxLength: 16
                example: 937aee55bbabd29b
              required: true
        '500':
          description: Internal Server Error
          headers:
            Request-Id:
              schema:
                type: string
                minLength: 16
                maxLength: 16
                example: 937aee55bbabd29b
              required: true
components:
  schemas:
    Consent:
      required:
        - consent
      type: object
      properties:
        consent:
          $ref: '#/components/schemas/ConsentRequestEnum'
        hpan:
          type: string
          minLength: 64
          maxLength: 64
          description: Pan hash to specify a single card. If blank the changes is referred to all cards linked to tax code
        services:
          type: array
          items:
            type: string
          description: List of the service involved by the modified. If blank the changes is referred to all services

    ConsentResponse:
      required:
        - consent
        - lastUpdateDate
      type: object
      properties:
        consent:
          $ref: '#/components/schemas/ConsentResponseEnum'
        lastUpdateDate:
          type: string
          format: date-time
          pattern: "dd/MM/yyyy HH:mm:ss"
        details:
          type: array
          items:
            $ref: '#/components/schemas/CardServiceConsent'
          description: List of services with assigned consent type, divided by card. Only present if consent type is Partial

    CardServiceConsent:
      required:
        - hpan
        - serviceConsents
      type: object
      properties:
        hpan:
          type: string
          minLength: 64
          maxLength: 64
          description: Pan hash to specify a single card. If blank the changes is referred to all cards linked to tax code
        serviceConsents:
          type: array
          items:
            $ref: '#/components/schemas/ServiceConsent'
          description: List of services with assigned consent type for the given card

    ServiceConsent:
      required:
        - consent
        - service
      type: object
      properties:
        consent:
          $ref: '#/components/schemas/ConsentRequestEnum'
        service:
          $ref: '#/components/schemas/ServiceEnum'

    ConsentError:
      required:
        - errorCode
        - description
      type: object
      properties:
        errorCode:
          type: string
          description: The code identifies the error
        description:
          type: string
          description: Error description
          example: [taxCode required, The new consent status is inconsistent with the current one]
    ConsentRequestEnum:
      description: Type of consent
      type: string
      enum:
        - Allow
        - Deny
    ConsentResponseEnum:
      description: Allow and Deny are applied to all hpans. Partial indicates to check in the details
      type: string
      enum:
        - Allow
        - Deny
        - Partial
    ServiceEnum:
      type: string
      enum:
        - FA
        - BPD