apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkmmsconsentmanageruat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tkmmsconsentmanageruat
  template:
    metadata:
      labels:
        app: tkmmsconsentmanageruat
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      nodeSelector:
        tkm-uat: true
      hostAliases:
        - ip: "10.70.73.228"
          hostnames:
            - "tkm-pgsql-pci-uat.postgres.database.azure.com"
        - ip: "10.70.73.37"
          hostnames:
            - "U87-EVH-pci-uat.servicebus.windows.net"
        - ip: "10.70.73.38"
          hostnames:
            - "tkmstorageblobuatpci.blob.core.windows.net"
        - ip: "10.230.9.5"
          hostnames:
            - "api.uat.platform.pagopa.it"
      volumes:
        - name: secrets-store-inline-consent-manager
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: tkm-consent-manager-spc-uat
            nodePublishSecretRef:
              name: tkm-consent-manager-kv-store-creds-uat
      containers:
        - name: tkmmsconsentmanageruat
          image: cstaruatregistry.azurecr.io/tkmmsconsentmanager
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 4Gi
              cpu: 500m
            limits:
              memory: 8Gi
              cpu: 1000m
          volumeMounts:
            - name: secrets-store-inline-consent-manager
              mountPath: /mnt/secrets-store
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  key: TZ
                  name: jvm
            - name: KAFKA_APPENDER_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  key: KAFKA_APPENDER_BOOTSTRAP_SERVERS
                  name: kafka-log-configuration
            - name: ENABLE_FILE_APPENDER
              valueFrom:
                secretKeyRef:
                  key: ENABLE_FILE_APPENDER
                  name: kafka-log-configuration
            - name: ENABLE_KAFKA_APPENDER
              valueFrom:
                secretKeyRef:
                  key: ENABLE_KAFKA_APPENDER
                  name: kafka-log-configuration
            - name: LOG_FILE
              valueFrom:
                secretKeyRef:
                  key: LOG_FILE
                  name: kafka-log-configuration
            - name: KAFKA_APPENDER_TOPIC
              valueFrom:
                secretKeyRef:
                  key: KAFKA_APPENDER_TOPIC
                  name: kafka-log-configuration
            - name: AZURE_KEYVAULT_PROFILE
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_PROFILE
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_CLIENT_ID
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_CLIENT_KEY
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_TENANT_ID
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_URI
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_URI
                  name: keyvault-connection-informations
            - name: CARD_MANAGER_URL
              valueFrom:
                secretKeyRef:
                  key: CARD_MANAGER_URL
                  name: tkmmsconsentmanager
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  key: DB_SERVER
                  name: tkmmsconsentmanager
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always
