apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkmmsconsentmanageruat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tkmmsconsentmanageruat
  template:
    metadata:
      labels:
        app: tkmmsconsentmanageruat
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      nodeSelector:
        tkm-uat: true
      hostAliases:
        - ip: "10.70.73.228"
          hostnames:
            - "tkm-pgsql-pci-uat.postgres.database.azure.com"
        - ip: "10.70.73.37"
          hostnames:
            - "U87-EVH-pci-uat.servicebus.windows.net"
        - ip: "10.70.73.38"
          hostnames:
            - "tkmstorageblobuatpci.blob.core.windows.net"
        - ip: "10.230.9.5"
          hostnames:
            - "api.uat.platform.pagopa.it"
      containers:
        - name: tkmmsconsentmanageruat
          image: cstaruatregistry.azurecr.io/tkmmsconsentmanager
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: keyvault-connection-informations
            - configMapRef:
                name: kafka-log-configuration
            - configMapRef:
                name: tkmmsconsentmanager
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always
